name: CI and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Install tetris package (editable)
        run: pip install -e .
      - name: Run tests
        run: pytest

  release:
    name: Build and Release Executable
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Install tetris package (editable)
        run: pip install -e .
      - name: Build executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/tetris/main.py
      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name tetris src/tetris/main.py
      - name: Upload Release Asset (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/tetris.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}