name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Install tetris package (editable)
        run: pip install -e .
      - name: Run tests
        run: pytest
      - name: Build executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/tetris/main.py
      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/tetris/main.py
      - name: Upload executable artifact (Linux)
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: tetris-linux
          path: dist/main
      - name: Upload executable artifact (Windows)
        if: matrix.os == 'windows-latest' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: tetris-windows
          path: dist/main.exe